---
- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Download Chef Development Kit
  get_url:
    url: "{{ chefdk_url }}"
    dest: "/usr/local/src/{{ chefdk_package }}"
    force: no

- name: Install Chef Development Kit
  apt:
    deb: "/usr/local/src/{{ chefdk_package }}"
