---
- name: Update apt-cache
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

#
# Install software
#
- name: ensure basic software is installed
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state="installed"
  with_items: [curl, tmux, screen, git, ncdu, tree, vim, wget, unzip ]

- name: install desktop software
  include: desktop_software.yml
  when: "'desktop' in group_names"

- name: grab bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /usr/local/bash-git-prompt
    update: no

- name: Janus VIM environment
  include: janus_vim.yml

#
# Bash environment
#
- name: build /etc/skel/.bashrc
  assemble:
    src: "../files/bashrc/{{ ansible_os_family }}"
    dest: /etc/skel/.bashrc
    mode: 0644
    owner: root
    group: root
