---
- name: Download Packer
  get_url:
    url: "{{ packer_url }}"
    dest: "/usr/local/src/{{ packer_archive }}"
    force: no

- name: Create Packer Destination Directory
  file:
    path: "/usr/local/packer-{{ packer_version }}"
    state: directory

- name: Unarchive Packer
  unarchive:
    copy: no
    creates: "/usr/local/packer-{{ packer_version }}/packer"
    dest: "/usr/local/packer-{{ packer_version }}/"
    src: "/usr/local/src/{{ packer_archive }}"

- name: Create Packer Profile
  template:
    src: "packer.j2"
    dest: "/etc/profile.d/packer.sh"
    mode: 775

