---
- name: build local .bashrc
  assemble:
    src: "../files/bashrc/{{ ansible_os_family }}"
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
